image: docker:latest

services:
  - docker:dind

stages:
  - build
  - notifications

variables:
  REGISTRY: "docker.io"
  REGISTRY_USER: "robpco"
  IMAGE_NAME: "static-website"
  REGISTRY_IMAGE: "${REGISTRY}/${REGISTRY_USER}/${IMAGE_NAME}"

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"

build:
  stage: build
  script:
    - docker build --pull --tag "${REGISTRY_IMAGE}:latest" .
    - docker push "${REGISTRY_IMAGE}:latest"
  only:
    variables:
      - $CI_COMMIT_TAG

notify_succcess_slack:
  stage: notifications
  allow_failure: true
  script:
    - apk --update add curl
    - date=$(date +%Y%m%d-%H%M)
    - './.cicd/notify_slack.sh "#builds" "$IMAGE_NAME - build success at $date"'
  when: on_success
  only:
    variables:
      - $CI_COMMIT_TAG

notify_fail_slack:
  stage: notifications
  allow_failure: true
  script:
    - apk --update add curl 
    - date=$(date +%Y%m%d-%H%M)
    - './.cicd/notify_slack.sh "#builds" "$IMAGE_NAME - build failure at $date"'
  when: on_failure
  only:
    variables:
      - $CI_COMMIT_TAG
