trigger:
  branches:
    include:
    - master  # This assumes you want to trigger the pipeline on changes to the 'main' branch. Adjust as needed.

pool:
  vmImage: 'nginx:alpine'

stages:
- stage: BuildAndPush
  jobs:
  - job: DockerBuildAndPush
    steps:
    - checkout: self  # This gets your source code from the linked GitHub repository

    - task: Docker@2
      inputs:
        containerRegistry: 'https://github.com/UnboltedHD2500'  # The name of your Docker registry service connection
        repository: 'UnboltedHD2500/docker-static-website'  # The name of your Docker repository on Docker Hub or another registry
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
