trigger:
- master

resources:
- repo: self

variables:
  containerRegistry: 'DockerHub'
  imageName: 'TestWeb'

stages:
- stage: Build
  displayName: 'Build and push Docker image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      name: 'Default'
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        command: 'buildAndPush'
        repository: 'peckma/TestWeb:latest'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'DockerHub'