trigger:
  branches:
    include:
    - master

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployToKubernetes
  jobs:
  - job: DeployJob
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'HomeKube'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deployment.yaml'