trigger:
  branches:
    include:
    - master

resources:
  - repo: self

stages:
- stage: BuildAndPush
  jobs:
  - job: DockerBuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'UnboltedHD2500/docker-static-website'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
